# Generated by Django 3.2.5 on 2021-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertask', '0002_alter_customuser_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
